// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: stack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PushServiceRequest) Reset() {
	*x = PushServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushServiceRequest) ProtoMessage() {}

func (x *PushServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushServiceRequest.ProtoReflect.Descriptor instead.
func (*PushServiceRequest) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{0}
}

func (x *PushServiceRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PushServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *PushServiceReply) Reset() {
	*x = PushServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushServiceReply) ProtoMessage() {}

func (x *PushServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushServiceReply.ProtoReflect.Descriptor instead.
func (*PushServiceReply) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{1}
}

func (x *PushServiceReply) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PopServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PopServiceRequest) Reset() {
	*x = PopServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stack_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopServiceRequest) ProtoMessage() {}

func (x *PopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopServiceRequest.ProtoReflect.Descriptor instead.
func (*PopServiceRequest) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{2}
}

func (x *PopServiceRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PopServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Empty  bool  `protobuf:"varint,5,opt,name=empty,proto3" json:"empty,omitempty"`
}

func (x *PopServiceReply) Reset() {
	*x = PopServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stack_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopServiceReply) ProtoMessage() {}

func (x *PopServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_stack_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopServiceReply.ProtoReflect.Descriptor instead.
func (*PopServiceReply) Descriptor() ([]byte, []int) {
	return file_stack_proto_rawDescGZIP(), []int{3}
}

func (x *PopServiceReply) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PopServiceReply) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

var File_stack_proto protoreflect.FileDescriptor

var file_stack_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a,
	0x12, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x10, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x50, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x3f, 0x0a, 0x0f, 0x50, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0x6f, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x30, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x13, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x03, 0x50, 0x6f, 0x70, 0x12, 0x12, 0x2e, 0x50, 0x6f, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x50, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stack_proto_rawDescOnce sync.Once
	file_stack_proto_rawDescData = file_stack_proto_rawDesc
)

func file_stack_proto_rawDescGZIP() []byte {
	file_stack_proto_rawDescOnce.Do(func() {
		file_stack_proto_rawDescData = protoimpl.X.CompressGZIP(file_stack_proto_rawDescData)
	})
	return file_stack_proto_rawDescData
}

var file_stack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stack_proto_goTypes = []interface{}{
	(*PushServiceRequest)(nil), // 0: PushServiceRequest
	(*PushServiceReply)(nil),   // 1: PushServiceReply
	(*PopServiceRequest)(nil),  // 2: PopServiceRequest
	(*PopServiceReply)(nil),    // 3: PopServiceReply
}
var file_stack_proto_depIdxs = []int32{
	0, // 0: StackService.Push:input_type -> PushServiceRequest
	2, // 1: StackService.Pop:input_type -> PopServiceRequest
	1, // 2: StackService.Push:output_type -> PushServiceReply
	3, // 3: StackService.Pop:output_type -> PopServiceReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stack_proto_init() }
func file_stack_proto_init() {
	if File_stack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stack_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stack_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stack_proto_goTypes,
		DependencyIndexes: file_stack_proto_depIdxs,
		MessageInfos:      file_stack_proto_msgTypes,
	}.Build()
	File_stack_proto = out.File
	file_stack_proto_rawDesc = nil
	file_stack_proto_goTypes = nil
	file_stack_proto_depIdxs = nil
}
